micronaut:
    server:
        port: 8080
    application:
        name: money-transfer-api

datasources:
  default:
    url: jdbc:h2:mem:todoDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
        show_sql: false
        format_sql: true